IdentityWithCookies/Controllers/AdminController.cs
using IdentityWithCookies.Identity;
using IdentityWithCookies.VİewsModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;

namespace IdentityWithCookies.Controllers
{
    public class AdminController : BaseController
    {
        
        public AdminController(UserManager<User> userManager, RoleManager<Role> roleManager) : base(userManager, null, roleManager)
        {
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Claims()
        {
            return View(User.Claims.ToList());
        }

        public IActionResult Users()
        {
            return View(_userManager.Users);
        }
        public IActionResult RoleCreate()
        {
            return View();
        }
        [HttpPost]
        public IActionResult RoleCreate(RoleViewModel roleViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(roleViewModel);
            }
            Role role = new Role { Name = roleViewModel.Name };
            IdentityResult result = _roleManager.CreateAsync(role).Result;
            if (!result.Succeeded)
            {
                AddModelError(result);
                return View(roleViewModel);
            }

            return RedirectToAction("roles");
        }
        public IActionResult Roles()
        {

            return View(_roleManager.Roles.ToList().Adapt<List<RoleViewModel>>());
        }
        public async Task<IActionResult> RoleDelete(string roleId)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Role bulunamadı");
                return RedirectToAction("Roles");
            }
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                ModelState.AddModelError("", "Role bulunamadı");
                return RedirectToAction("Roles");
            }

            var result = await _roleManager.DeleteAsync(role);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Role bulunamadı");
                AddModelError(result);
                return RedirectToAction("Roles");
            }

            return RedirectToAction("Roles");

        }
        public IActionResult RoleUpdate(string roleId)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Role bulunamadı");
                return RedirectToAction("Roles");
            }
            var role = _roleManager.FindByIdAsync(roleId).Result;
            if (role == null)
            {
                ModelState.AddModelError("", "Role bulunamadı");
                return RedirectToAction("Roles");
            }
            return View(role.Adapt<RoleViewModel>());
        }
        [HttpPost]
        public async Task<IActionResult> RoleUpdate(RoleViewModel roleView)
        {
            if (!ModelState.IsValid)
            {
                return View(roleView);
            }
            var role = await _roleManager.FindByIdAsync(roleView.Id);
            if (role != null)
            {
                role.Name = roleView.Name;
                var result = await _roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Roles");
                }
                AddModelError(result);
            }
            return RedirectToAction("Roles");

        }
        public async Task<IActionResult> RoleAssign(string Id)
        {
            if (ModelState.IsValid)
            {

                var user = _userManager.FindByIdAsync(Id).Result;
                if (user != null)
                {
                    ViewData["userName"] = user.UserName;
                }
                List<Role> AllRole = _roleManager.Roles.ToList();
                List<string> userHaveRoleString = await _userManager.GetRolesAsync(user) as List<string>;
                List<Role> UserHave = new List<Role>();
                userHaveRoleString.ForEach(i => UserHave.Add( _roleManager.FindByNameAsync(i).Result));
                if(UserHave==null)
                {
                    UserHave = new List<Role>();
                }
                
                List<Role> UserDontHave = new List<Role>();
                RoleList Roles = new RoleList();
                UserDontHave = AllRole.Where(i => !(UserHave.Any(y => y.Name.Contains(i.Name)))).ToList();
                Roles.OwnerRole = UserHave.Adapt<List<RoleEditViewModel>>();
                Roles.AddRole = UserDontHave.Adapt<List<RoleEditViewModel>>();
                Roles.DeleteRole = UserHave.Adapt<List<RoleEditViewModel>>();
                Roles.UserId = user.Id;
                return View(Roles);
            }
            ModelState.AddModelError("", "Bir hata oluştu");
            return RedirectToAction("Users");
        }
        [HttpPost]
        public async Task<IActionResult> RoleAssign(RoleList Roles)
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(Roles.UserId);
                
                if(Roles.AddRole.Any(i=>i.Exist))
                {
                    foreach (var item in Roles.AddRole.Where(i=>i.Exist))
                    {
                        IdentityResult result=await _userManager.AddToRoleAsync(user, item.Name);
                        if(!result.Succeeded)
                        {
                            AddModelError(result);
                            return View(Roles);
                        }
                    }
                }
                if(Roles.DeleteRole.Any(i=>i.Exist))
                {
                    foreach(var item in Roles.DeleteRole.Where(i=>i.Exist))
                    {
                        IdentityResult result = await _userManager.RemoveFromRoleAsync(user, item.Name);
                        if(!result.Succeeded)
                        {
                            AddModelError(result);
                            return View(Roles);
                        }
                    }
                }
                return RedirectToAction("RoleAssign", "admin",new { Id=Roles.UserId});
            }
            return View(Roles);
        }
    }
}

IdentityWithCookies/Controllers/MemberController.cs
using IdentityWithCookies.Enums;
using IdentityWithCookies.Identity;
using IdentityWithCookies.VİewsModel;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityWithCookies.Controllers
{
    [Authorize]
    public class MemberController : BaseController
    {
        
        public MemberController(UserManager<User> userManager, SignInManager<User> signManager):base(userManager,signManager)
        {
           
        }

        public  IActionResult Index()
        {
            User user = CurrentUser();
            UserViewModel viewModel = user.Adapt<UserViewModel>();
            return View(viewModel);
        }
        [Authorize(Policy ="IstanbulPolicy")]
        public IActionResult Istanbul()
        {
            return View();
        }


        [Authorize(Roles ="Editor,Admin")]
        public IActionResult Editor()
        {
            return View();
        }
        [Authorize(Roles = "Manager,Admin")]
        public IActionResult Manager()
        {
            return View();
        }
        public IActionResult UserEdit( )
        {
            var user = CurrentUser();

            UserViewModel userView = user.Adapt<UserViewModel>();
            ViewData["type"]= new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Selected=false,Text=Gender.Belirtilmemiş.ToString(),Value=((int)Gender.Belirtilmemiş).ToString()},
                new SelectListItem { Selected=false,Text=Gender.Bay.ToString(),Value=((int)Gender.Bay).ToString()},
                new SelectListItem { Selected=false,Text=Gender.Bayan.ToString(),Value=((int)Gender.Bayan).ToString()},

            });
            

            return View(userView);
        }
        [HttpPost]
        public async Task<IActionResult> UserEdit(UserViewModel userview,IFormFile userPicture)
        {
            ModelState.Remove("Password");
            if (!ModelState.IsValid)
            {
                return View(userview);

            }
            var user = CurrentUser();

            if (userPicture!=null && userPicture.Length>0)
            {
                var userPath = Guid.NewGuid().ToString() + Path.GetExtension(userPicture.FileName);
                var pathss = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\picture", userPath);

                using(var stream =new FileStream(pathss, FileMode.Create))
                {
                    await userPicture.CopyToAsync(stream);
                    user.PictureUrl =$"/picture/"+userPath;
                }
            }


            user.UserName = userview.UserName;
            user.Email = userview.Email;
            user.PhoneNumber = userview.PhoneNumber;
            user.City = userview.City;
            user.BirthDay = userview.BirthDay;
            user.Gender = ((int)userview.Gender);


            var result = await _userManager.UpdateAsync(user);
            if(!result.Succeeded)
            {
                AddModelError(result);
                return View(userview);
            }
            await _userManager.UpdateSecurityStampAsync(user);
            await _signInManager.SignOutAsync();
            await _signInManager.SignInAsync(user, true);
            return RedirectToAction("Index");
        }


        public IActionResult PasswordChange()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeViewModel passwordChangeViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(passwordChangeViewModel);
            }
            var user = CurrentUser();
            if (user == null)
            {
                return View(passwordChangeViewModel);
            }

            var result = await _userManager.ChangePasswordAsync(user, passwordChangeViewModel.PasswordOld, passwordChangeViewModel.PasswordNew);
            if (!result.Succeeded)
            {
                AddModelError(result);
                return View(passwordChangeViewModel);
            }

            await _userManager.UpdateSecurityStampAsync(user);
            return RedirectToAction("login", "Home");
        }
        public IActionResult AccessDenied()
        {
            return View();
        }
        public void LogOut()
        {
            var user = CurrentUser();
            _signInManager.SignOutAsync();
        }
    }
}

IdentityWithCookies/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityWithCookies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Admin">Admin Ana Sayfa</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:10px;">
        <div class="row">
            <div class="col-md-8">
                @RenderBody()
            </div>
            <div class="col-md-4">
                <h3>Menü</h3>

                <a class="btn btn-danger btn-block" asp-action="Claims" asp-controller="Admin">üye claims</a>

                <a class="btn btn-danger btn-block" asp-action="Users" asp-controller="Admin">Üyeler</a>

                <a class="btn btn-danger btn-block" asp-action="Roles" asp-controller="Admin">Roller</a>

                <a class="btn btn-danger btn-block" asp-action="Logout" asp-controller="Member" asp-route-returnUrl="/Home/Index">Çıkış yap</a>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IdentityWithCookies - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        <b></b>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IdentityWithCookies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityWithCookies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Identity</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="home" asp-action="signup">Sign Up <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/home/login">Login</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IdentityWithCookies - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>